### ISSUE TITLE
AssertionError: The environment must specify an observation space.

### ISSUE THREAD

**Issue by DrHoofman** [dickreuter/neuron_poker#81]
tried to start and get the following:
`Screenloglevel: 20
INFO - Initializing program
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    command_line_parser()
  File "main.py", line 65, in command_line_parser
    runner.random_agents()
  File "main.py", line 107, in random_agents
    self.env = gym.make(env_name, initial_stacks=self.stack, render=self.render)
  File "/Users/stefanschumm/anaconda3/envs/neuron_poker/lib/python3.7/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/Users/stefanschumm/anaconda3/envs/neuron_poker/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 26, in __init__
    ), "The environment must specify an observation space. https://www.gymlibrary.dev/content/environment_creation/"
AssertionError: The environment must specify an observation space. https://www.gymlibrary.dev/content/environment_creation/`

**Comment by DrHoofman** [comment]
What I have to do to get it running?

**Comment by PhPeKe** [comment]
I could "solve" it by installing gym==0.24.0 but now im running into other issues with pyglet

**Comment by PhPeKe** [comment]
gym==0.24.0
pyglet==1.5.11

does the trick

**Comment by PhPeKe** [comment]
gym==0.23.0
pyglet==1.5.11
works for me
